Revisiting Neighbor View
hu-macsy/dhb pull request #11
Opened 2024-10-29 15:30 UTC by c-bebop

The Neighbor View Classes are an important tool to iterate over neighbors N(u) of vertex u. The usage of it is fairly simple, yet lagged the feature of returning the vertex u as the _source of neighborhood N(u)_. A simple get function `source()` has been added to the class incl. tests. 

As a finish you will find explicit type declarations for `iterator` and (east) `const` correctness.

2024-10-30 12:59 UTC, bernlu requested changes
Some general comments:
- `iterator` should be a capitalized name as it is a class
- `m_u` and `m_g` are very unspecific member variable names, but this PR is probably not the place to change them

2024-10-30 12:59 UTC, bernlu commented on include/dhb/dynamic_hashed_blocks.h
> +        const_iterator cend() const { return m_g->m_vertices[m_u].cvalid_end(); }
why is one of these iterators called `valid_end` and the other `end`? Is there a difference? The name suggests `valid_end == end - 1` which makes this function seem incorrect?

2024-10-30 12:59 UTC, bernlu commented on include/dhb/dynamic_hashed_blocks.h
>          ConstNeighborView(const Matrix* g, Vertex u) : m_g{g}, m_u{u} {}
Inconsistent east vs west const (maybe also in other places? do we have clang-format in this project?)

2024-10-30 12:59 UTC, bernlu commented on include/dhb/dynamic_hashed_blocks.h
> +        iterator end() const { return m_g->m_vertices[m_u].cvalid_end(); }
same comment again about the valid/end iterator

2024-10-31 08:27 UTC, c-bebop commented on include/dhb/dynamic_hashed_blocks.h
> +        const_iterator cend() const { return m_g->m_vertices[m_u].cvalid_end(); }
Think of a vector where we pre-allocate (`reserve()`) a chunk of memory. In order to add an element to that vector (`push_back()`) we need to keep track of the  _end_ of the pre-allocated memory chunk and the _end_ of the currently used and therefore _valid_ segment. In our case we call `end()` the actual end of the pre-allocated memory chunk, and `valid_end()` as the end of the currently used valid segment of the block. 

Does this make sense?

2024-10-31 08:28 UTC, c-bebop commented on include/dhb/dynamic_hashed_blocks.h
> +        iterator end() const { return m_g->m_vertices[m_u].cvalid_end(); }
The [my comment](https://github.com/hu-macsy/dhb/pull/11#discussion_r1824066427).

2024-10-31 09:21 UTC, bernlu approved these changes

2024-10-31 11:04 UTC, merged